formatter: markdown document
output-mode: inject
header-from: docs/_header.md
sections:
  show:
    - header
    - footer
    - inputs
    - outputs
    - providers
    - requirements
    - resources
    - modules
