name: TF Docs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  generate-vm-docs:
    uses: ./.github/workflows/generate-docs.yml
    with:
      module_path: './proxmox/vm'
      output_file: 'README.md'

  generate-lxc-docs:
    uses: ./.github/workflows/generate-docs.yml
    with:
      module_path: './proxmox/lxc'
      output_file: 'README.md'

  generate-cloud-img-docs:
    uses: ./.github/workflows/generate-docs.yml
    with:
      module_path: './proxmox/cloud-img-download'
      output_file: 'README.md'

  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: update Terraform docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
