name: TF Docs Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  generate-vm-docs:
    uses: ./.github/workflows/generate-docs.yml
    with:
      module_path: "./proxmox/vm"
      output_file: "README.md"
      container_image: "ghcr.io/shakir85/tf-tools:latest"

  commit-changes:
    runs-on: ubuntu-latest
    needs:
      - generate-vm-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Git Setup
        uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: update Terraform docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
