name: Generate Terraform Docs

on:
  workflow_call:
    inputs:
      module_path:
        type: string
        description: 'The path to the Terraform module to document'
        required: true
      output_file:
        type: string
        description: 'The README file to update'
        required: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shakir85/tf-tools:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Git Setup
        uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - name: Fetch latest changes
        run: |
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Generate Docs
        run: terraform-docs markdown document ${{ inputs.module_path }} --output-file ${{ inputs.output_file }} --output-mode inject
