name: TF Lint

on:
  workflow_call:

jobs:
  code-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shakir85/tf-tools:latest

    steps:
      - uses: shakir85/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - run: |
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Format Terraform code
        run: terraform fmt -recursive

      - name: Lint Terraform code
        run: tflint --recursive

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: auto-format Terraform files [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
