name: "Terraform CI Pipeline"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'proxmox/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  # check-vm-changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     vm_changed: ${{ steps.filter.outputs.vm }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - id: filter
  #       uses: dorny/paths-filter@v3
  #       with:
  #         filters: |
  #           vm:
  #             - 'proxmox/vm/**'
  # test:
  #   needs: [lint]
  #   uses: ./.github/workflows/test.yml
  #   # if: needs.check-vm-changes.outputs.vm_changed == 'true'
  #   with:
  #     api_token: ${{ secrets.PROXMOX_API_TOKEN }} # vscode: ignore
