name: "Terraform CI Pipeline"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "terraform/**"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  docs:
    needs: lint
    uses: ./.github/workflows/docs.yml
    with:
      path: "terraform/"
